#!/bin/env python
#-*- coding:utf-8 -*-

# show global status
monit_keys = [
    ('Com_select', 'counter'),
    ('Com_insert', 'counter'),
    ('Com_update', 'counter'),
    ('Com_delete', 'counter'),
    ('Com_commit', 'counter'),
    ('Com_rollback', 'counter'),
    ('Questions', 'counter'),
    ('Handler_commit', 'counter'),
    ('Handler_delete', 'counter'),
    ('Handler_read_first', 'counter'),
    ('Handler_rollback', 'counter'),
    ('Handler_update', 'counter'),
    ('Handler_write', 'counter'),
    ('Open_files', 'gauge'),
    ('Opened_files', 'gauge'),
    ('Open_tables', 'gauge'),
    ('Opened_tables', 'gauge'),
    ('Open_table_definitions', 'gauge'),
    ('Opened_table_definitions', 'gauge'),
    ('Innodb_row_lock_waits', 'gauge'),
    ('Innodb_row_lock_current_waits', 'gauge'),
    ('Innodb_buffer_pool_read_requests', 'counter'),
    ('Innodb_buffer_pool_write_requests', 'counter'),
    ('Innodb_buffer_pool_pages_flushed', 'counter'),
    ('Innodb_buffer_pool_reads', 'counter'),
    ('Innodb_buffer_pool_bytes_dirty', 'counter'),
    ('Innodb_data_fsyncs', 'counter'),
    ('Innodb_data_pending_fsyncs', 'counter'),
    ('Innodb_data_pending_reads', 'counter'),
    ('Innodb_data_pending_writes', 'counter'),
    ('Innodb_data_read', 'counter'),
    ('Innodb_data_reads', 'counter'),
    ('Innodb_data_written', 'counter'),
    ('Innodb_data_writes', 'counter'),
    ('Innodb_buffer_pool_pages_total', 'gauge'),
    ('Innodb_buffer_pool_pages_free', 'gauge'),
    ('Innodb_buffer_read_hits', 'gauge'),
    ('Innodb_log_waits', 'gauge'),
    ('Innodb_page_size', 'gauge'),
    ('Innodb_row_lock_time', 'gauge'),
    ('Innodb_row_lock_time_avg', 'gauge'),
    #('Connection_errors_internal', 'gauge'),
    #('Connection_errors_max_connections', 'gauge'),
    ('Threads_connected', 'gauge'),
    ('Connections', 'counter'),
    ('Threads_running', 'gauge'),
    ('Aborted_connects', 'counter'),
    ('Slow_queries', 'counter'),
    ('Select_full_join', 'gauge'),
    ('Select_scan', 'counter'),
    ('Threads_created', 'counter'),
    ('Created_tmp_disk_tables', 'gauge'),
    ('Created_tmp_files', 'gauge'),
    ('Created_tmp_tables', 'gauge'),
    ('Binlog_cache_disk_use', 'gauge'),
    ('Binlog_cache_use', 'gauge'),
    ('Slave_running', 'counter'),
    ('Thread_cache_hits', 'gauge'),
    ('Writes', 'counter'), 
    ('Key_writes', 'counter'), 
    ('Key_write_requests', 'counter'), 
    ('Key_reads', 'counter'), 
    ('Key_read_requests', 'counter'), 
    ('key_buffer_read_hits', 'gauge'),
    ('Key_buffer_write_hits', 'gauge'),
    ('Query_cache_hits', 'gauge'),
    ('Qcache_inserts', 'counter'),
    ('Qcache_lowmem_prunes', 'counter'),
    ('Qcache_queries_in_cache', 'counter'),
    ('Qcache_total_blocks', 'counter'),
    ('Qcache_free_memory', 'gauge'),
    ('Qcache_free_blocks', 'gauge'),
    ('Qcache_not_cached', 'counter'),
]

slave_keys = [
    ('Slave_IO_Running', 'gauge'),
    ('Slave_SQL_Running', 'gauge'),
    ('Seconds_Behind_Master', 'gauge'),
]
